website/models.py
from flask import Flask, render_template, request, redirect, url_for
import sqlite3




app = Flask(__name__)

def init_db():
    conn = sqlite3.connect('birthdays.db')
    cur = conn.cursor()
    cur.execute('''CREATE TABLE IF NOT EXISTS birthdays
                   (id INTEGER PRIMARY KEY, first_name TEXT, last_name TEXT, relationship TEXT, dob TEXT, gift_ideas TEXT)''')
    conn.commit()
    conn.close()

init_db()


@models.route('/')
def index():
    return render_template('BT-EnterBDay.html')

@models.route('/BT-EnterBDay.html', methods=['POST'])
def enterBDay():
    first_name = request.form['inputFirstName']
    last_name = request.form['inputLastName']
    relationship = request.form['relationship']
    dob = request.form['dob']
    gift_ideas = request.form['giftIdeas']

    conn = sqlite3.connect('birthdays.db')
    cur = conn.cursor()
    cur.execute('''INSERT INTO birthdays (first_name, last_name, relationship, dob, gift_ideas) VALUES (?, ?, ?, ?, ?)''', (first_name, last_name, relationship, dob, gift_ideas))
    conn.commit()
    conn.close()

    return redirect(url_for('index'))

@models.route('/BT-ViewBDays.html', methods=['GET'])
def displayBDays():
    conn = sqlite3.connect('birthdays.db')
    cur = conn.cursor()
    cur.execute('''SELECT * FROM birthdays''')
    data = cur.fetchall()
    conn.close()

    return render_template('birthdays.html', data=data)

if __name__ == '__main__':
    app.run(debug=True)

website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'webApps'

    from .views import views

    app.register_blueprint(views, url_prefix='/')
    

    return app

website/views.py
from flask import Blueprint, render_template, request, Flask
import sqlite3

views = Blueprint('views', __name__)

app = Flask(__name__)
def init_db():
    conn = sqlite3.connect('birthdays.db')
    cur = conn.cursor()
    cur.execute('''CREATE TABLE IF NOT EXISTS birthdays
                   (id INTEGER PRIMARY KEY, first_name TEXT, last_name TEXT, relationship TEXT, dob TEXT, gift_ideas TEXT)''')
    conn.commit()
    conn.close()

init_db()

@views.route('/')
def home():
    return render_template("BT-Intro.html")

@views.route('/BT-Intro.html')
def intro():
    return render_template("BT-Intro.html")

@views.route('/BT-EnterBDay.html')
def enterBDay():
    return render_template("BT-EnterBDay.html")

@views.route('/BT-EnterBDay.html', methods=['POST'])
def enterBDay2():
    first_name = request.form['inputFirstName']
    last_name = request.form['inputLastName']
    relationship = request.form['relationship']
    dob = request.form['dob']
    gift_ideas = request.form['giftIdeas']

    conn = sqlite3.connect('birthdays.db')
    cur = conn.cursor()
    cur.execute('''INSERT INTO birthdays (first_name, last_name, relationship, dob, gift_ideas) VALUES (?, ?, ?, ?, ?)''', (first_name, last_name, relationship, dob, gift_ideas))
    conn.commit()
    conn.close()
    return render_template("BT-EnterBDay.html")

@views.route('/BT-ViewBDay.html')
def viewBDay():
    conn = sqlite3.connect('birthdays.db')
    cur = conn.cursor()
    cur.execute('''SELECT * FROM birthdays''')
    data = cur.fetchall()
    conn.close()

    return render_template('BT-ViewBDay.html', data=data)

website/templates/BT-EnterBDay.html
<!-- This is a website for HW4 of CSCI 4710 -->
<!-- This is the enter birthday page-->
<html>
	<head>
		<meta charset="utf-8">
  		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		<title>Birthday Tracker</title>
		<style>
			ul {
				list-style-type: none;
				margin-top: 10;
				padding: 0;
			 	overflow: hidden;
			  	background-color: #3F2D4C;
			}

			li {
				padding-right: 10;
			  	float: right;
			}

			li a {
				font-family: 'Verdana';
				font-size: 16px;
				font-weight: bold;
			  	display: block;
			  	color: C4B8B4;
			  	text-align: center;
			  	padding: 14px 16px;
			  	text-decoration: none;
			}

			a:hover {
				background-color: 918398;
				color: C4B8B4;
				border-style: solid;
				border-color: C4B8B4;
				border-width: 5px;
				margin: -5px;
			}
			label {
				font-family: 'Verdana';
				font-style: normal;
				margin-right: auto;
				margin-left: 10%;
				margin-top: 30px;
			}
			input[type='text'] {
				font-family: 'Verdana';
				width: 50%;
				height: 35px;
				font-size: 16px;
				border-radius: 5px;
				margin-left: 10%;
				margin-right: 10%;
				margin-top: 30px;
			}
			input[type='date'] {
				font-family: 'Verdana';
				width: 50%;
				height: 35px;
				font-size: 16px;
				border-radius: 5px;
				margin-left: 10%;
				margin-right: 10%;
				margin-top: 30px;
			}
		</style>
	</head>

	<body style="background-color: C4B8B4;">

		<ul>
			<li><a href="BT-ViewBDay.html">View Birthdays</a></li>
			<li><a class="active" href="BT-EnterBDay.html">Enter Birthday</a></li>
		  	<li><a href="BT-Intro.html">Introduction</a></li>
		  	<li style="float: left;"><a style="pointer-events: none;">Birthday Tracker</a></li>
		</ul>

		<div class="form-group" style="text-align:left; font-family: 'Verdana'; font-size: 16px; width: 40%; margin-left: auto; margin-right: auto; margin-top: 100px;color: black; background-color: 918398; padding: 15px; border-radius: 15px;">
			<form class="form-horizontal" action="{{ url_for('views.enterBDay') }}" method="post">
				<label type="label" class="control-label" for="inputFirstName">First Name:&nbsp;&nbsp;&nbsp;</label>
				<input type="text" id="inputFirstName" name="inputFirstName" placeholder="First Name">
				<br>
				<label type="label" class="control-label" for="inputLastName">Last Name:&nbsp;&nbsp;&nbsp;</label>
				<input type="text" id="inputLastName" name="inputLastName" placeholder="Last Name">
				<br>
				<label type="label" class="control-label" for="relationship">Relationship:</label>
				<input type="text" id="relationship" name="relationship" placeholder="Relationship">
				<br>
				<label type="label" class="control-label" for="dob">Date of Birth:</label>
        		<input type="date" id="dob" name="dob" placeholder="MM/DD/YYY" type="text"/>
        		<br>
				<label type="label" class="control-label" for="relationship">Gift Ideas:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
				<textarea id="giftIdeas" name="giftIdeas" placeholder="Gift Ideas" style=" font-family: 'Verdana'; width: 50%; height: 100px; font-size: 16px; border-radius: 5px;  margin-left: 10%; margin-right: auto; margin-top: 30px;"></textarea>
        		<br>
				<div class="text-center">
					<button type="submit" class="btn btn-primary" style="height: 50px; width: 100px; font-size: 20px; margin-left: auto; margin-right: auto; margin-top: 30px;" onclick="submitBDay()">Submit</button>
				</div>
			</form>
		</div>


		
		<script>
			function resetForm(){
				// This function is pretty obvious, just resets to form values to their defaults after being called
				document.getElementById('form').reset();
			}
			function submitBDay(){
				// Add the stuff to submit the form data to the database here
				// You can look at addpeople.html for how it was done last time
			}
		</script>

	</body>
</html>

website/templates/BT-Intro.html
<!-- This is a website for HW4 of CSCI 4710 -->
<!-- This is the introduction page-->
<html>
	<head>
		<meta charset="utf-8">
  		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		<title>Birthday Tracker</title>
		<style>
			ul {
				list-style-type: none;
				margin-top: 10;
				padding: 0;
			 	overflow: hidden;
			  	background-color: #3F2D4C;
			}

			li {
				padding-right: 10;
			  	float: right;
			}

			li a {
				font-family: 'Verdana';
				font-size: 16px;
				font-weight: bold;
			  	display: block;
			  	color: C4B8B4;
			  	text-align: center;
			  	padding: 14px 16px;
			  	text-decoration: none;
			}

			a:hover {
				background-color: 918398;
				color: C4B8B4;
				border-style: solid;
				border-color: C4B8B4;
				border-width: 5px;
				margin: -5px;
			}		
		</style>
	</head>

	<body style="background-color: C4B8B4;">

		<ul>
			<li><a href="BT-ViewBDay.html">View Birthdays</a></li>
			<li><a href="BT-EnterBDay.html">Enter Birthday</a></li>
		  	<li><a class="active" href="BT-Intro.html">Introduction</a></li>
		  	<li style="float: left;"><a style="pointer-events: none;">Birthday Tracker</a></li>
		</ul>

		<p title="Birthday Tracker Introduction" style="text-align:center; font-family: 'Verdana'; font-size: 20px; width: 600px; margin-left: auto; margin-right: auto; margin-top: 100px;color: black; background-color: 918398; padding: 15px; border-radius: 15px;">
		<br>
			Welcome to Birthday Tracker!
		<br>

		<br>
		Created by: Alex Button, Shannen Geller, Sepehr Saljooghi
		<br>

		<br>
		We are here to help keep track of all the important people in your lives birthdays! Save them here and never forget a birthday again!
			
		</p>


	</body>
</html>

website/templates/BT-ViewBDay.html
<!-- This is a website for HW4 of CSCI 4710 -->
<!-- This is the enter birthday page-->
<html>
	<head>
		<meta charset="utf-8">
  		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		<title>Birthday Tracker</title>
		<style>
			ul {
				list-style-type: none;
				margin-top: 10;
				padding: 0;
			 	overflow: hidden;
			  	background-color: #3F2D4C;
			}

			li {
				padding-right: 10;
			  	float: right;
			}

			li a {
				font-family: 'Verdana';
				font-size: 16px;
				font-weight: bold;
			  	display: block;
			  	color: C4B8B4;
			  	text-align: center;
			  	padding: 14px 16px;
			  	text-decoration: none;
			}

			a:hover {
				background-color: 918398;
				color: C4B8B4;
				border-style: solid;
				border-color: C4B8B4;
				border-width: 5px;
				margin: -5px;
			}
			.col {
				border: 3px solid;
				border-color: #3F2D4C;
				border-collapse: collapse;
				padding: 5px;
			}
			.col2{
				border: 3px solid;
				border-color: #3F2D4C;
				border-collapse: collapse;
			}
		</style>
	</head>

	<body style="background-color: C4B8B4;">

		<ul>
			<li><a class="active" href="BT-ViewBDay.html">View Birthdays</a></li>
			<li><a href="BT-EnterBDay.html">Enter Birthday</a></li>
		  	<li><a href="BT-Intro.html">Introduction</a></li>
		  	<li style="float: left;"><a style="pointer-events: none;">Birthday Tracker</a></li>
		</ul>

		
		<div style="width: 40%; background-color: 918398; padding: 15px; border-radius: 15px; margin-left: auto; margin-right: auto; margin-top: 100px; width: 40%; text-align:center;">
			<table style="margin-left: auto; margin-right: auto; text-align:left; font-family: 'Verdana'; font-size: 14px; color: black; border: 1px solid; border-color: #3F2D4C; border-collapse: collapse; background-color: lightgray; width: 80%;">
				<thead>
				  <tr class="col2">
					<th class="col">First Name</th>
					<th class="col">Last Name</th>
					<th class="col">Relationship</th>
					<th class="col">Date of Birth</th>
					<th class="col">Gift Ideas</th>
				  </tr>
				</thead>
				<tbody>
				  {% for row in data %}
				  <tr class="col2">
					<td class="col">{{ row[1] }}</td>
					<td class="col">{{ row[2] }}</td>
					<td class="col">{{ row[3] }}</td>
					<td class="col">{{ row[4] }}</td>
					<td class="col">{{ row[5] }}</td>
				  </tr>
				  {% endfor %}
				</tbody>
			</table>
		</div>


	</body>
</html>

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, inital-scale=1"/>
        <link 
            rel="stylesheet" 
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />

        <!-- this title can be overwritten so the title can change depending on what html page we are on -->
        <title>
            {% block title %} {% endblock %}
        </title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type = "button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id = "navbar">
            <div class="navbar-nav">
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signup" href="/sign-up">Sign Up</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                <a class="nav-item nav-link" id="home" href="/">Home</a>
            </div>
        </div>

        </nav>

        <div class = "container">
            {%block content%} {% endblock%}
        </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    </body>
</html>